name: production deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      # 「./dist」にビルド結果が生成する。好きなビルドに変えましょう。
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build

      # Netlifyにデプロイする。「--dir=./dist」の部分はビルド結果ができあがるディレクトリ名に変えましょう。
      - run: npx netlify-cli deploy --dir=./dist
        env:
          NETLIFY_SITE_ID: ${{ 7804956b-4777-4675-863d-fd5e1837ebd6 }}
          NETLIFY_AUTH_TOKEN: ${{ hHh8FYjIPdHgVMIucOZedhuVr4Sy8a_FgnWhTAlSM7A }}